# Generated by Django 2.2 on 2019-11-24 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0002_auto_20191124_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='creates',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 13, 35, 59, 139743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='register1',
            name='rid',
            field=models.CharField(max_length=20),
        ),
    ]
