# Generated by Django 2.2 on 2019-11-24 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0005_auto_20191124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='creates',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 13, 49, 8, 22865, tzinfo=utc)),
        ),
    ]
