# Generated by Django 2.2 on 2019-11-26 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0018_auto_20191124_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='creates',
            field=models.DateField(default=datetime.datetime(2019, 11, 26, 6, 57, 50, 46687, tzinfo=utc)),
        ),
    ]
