# Generated by Django 2.2 on 2019-11-24 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0009_auto_20191124_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='pkid',
            fields=[
                ('idg', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('blood_group', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('creates', models.DateField(default=datetime.datetime(2019, 11, 24, 14, 2, 0, 268035, tzinfo=utc))),
                ('number', models.CharField(max_length=25)),
                ('rgid', models.ForeignKey(on_delete=False, to='saiapp.pkid')),
            ],
        ),
        migrations.DeleteModel(
            name='register1',
        ),
    ]
