# Generated by Django 2.2 on 2019-11-24 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0011_auto_20191124_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='creates',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 14, 10, 33, 202373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='register1',
            name='rgid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
