# Generated by Django 2.2 on 2019-11-24 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saiapp', '0013_auto_20191124_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='creates',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 14, 20, 57, 589086, tzinfo=utc)),
        ),
    ]
